name: Publish Version
on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      shouldSyncItems:
        description: "Should Sync Items to Firebase"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - name: check-version
        id: check-version
        uses: twilioquest/twilioquest-base/actions/check-version@main
      - name: "publish package"
        # We only want to publish to npm if we have a new
        # version of this package.
        if: steps.check-version.outputs.isNewVersion == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "sync items to twilioquest-server"
        # We should need to sync items if this is a new
        # version of twilioquest-base.
        if: steps.check-version.outputs.isNewVersion == 'true' && inputs.shouldSyncItems
        # External action hardcoded to specific commit SHA to ensure
        # this action is not updated to do something malicious without
        # us intentionally updating.
        #
        # branch: ssh-deploy-key, last updated: Aug. 1, 2022
        uses: cpina/github-action-push-to-another-repository@b5ac509f7b2dc62ec43608515039593fae596689
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_ITEMS_SYNC_KEY }}
        with:
          source-directory: "items"
          destination-github-username: "twilio"
          destination-repository-name: "twilioquest-server"
          user-email: svc.twilioquest@twilio.com
          commit-message: "Sync items from twilioquest-base"
          target-branch: next
          target-directory: "functions/views/items"
